# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Osipchuk / donqustix
email: donqustix@gmail.com
description: Welcome to my personal website dedicated to everything related to programming, science, and other funny things!
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
google_site_verification: Y9l9eMPyhdxpC0ROM-97w3EaFCUA42n58SXu3WmppJM
github_url: https://github.com/donqustix/
linkedin_url: https://www.linkedin.com/in/alex-osipchuk-47037813a/
social:
  name: Alex Osipchuk
  links:
    - linkedin_url
    - github_url

# Build settings
markdown: kramdown
#theme: jekyll-donqustix-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - 
    scope:
        path: ""
        type: "pages"
    values:
        layout: "default"
  -
    scope:
        path: "_posts"
        type: "posts"
    values:
        header_file: "post_header.md"
        mathjax: false
        mermaid: false
        layout: "post"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
